// Generated by CoffeeScript 1.6.3
requirejs.config({
  baseUrl: '../js',
  paths: {
    apps: 'apps',
    libs: 'libs'
  },
  shim: {
    'apps/register-message': {
      deps: ['libs/jquery', 'apps/register-message-state', 'apps/register-checker-password'],
      exports: 'Message'
    },
    'apps/bindcsdn-third-part': {
      deps: ['libs/jquery']
    }
  }
});

requirejs(['apps/register-checker', 'apps/bindcsdn-third-part'], function(checker, bindcsdn) {
  checker.init();
  bindcsdn.init();
});
